# Generated by Django 4.1.4 on 2022-12-15 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocName', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, choices=[('alex', 'alex'), ('cairo', 'cairo')], max_length=15, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('soolid', 'soolid'), ('cardef', 'cardef'), ('ssesf', 'ssesf'), ('sefg', 'sefg'), ('cardef', 'cardef')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='uplaoad')),
                ('phone', models.IntegerField(blank=True, default=1, null=True)),
                ('are_you_doctor', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weatingHours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workingHours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('img', models.ImageField(blank=True, upload_to='uplaoad')),
                ('phone', models.IntegerField(blank=True, default=1, null=True)),
                ('are_you_doctor', models.BooleanField(blank=True, null=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_system.profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
