# Generated by Django 4.1.4 on 2022-12-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
