# Generated by Django 4.1.4 on 2022-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_add_are_you_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='are_you_doctor',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
